version: "3.9"
services:
  server:
    build: .
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/configurations
    networks:
      - my_spring-cloud-network

networks:
  my_network:
    driver: bridge
