version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  server:
    build: .
    restart: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=development
    networks:
      - my_spring-cloud-network

networks:
  my_spring-cloud-network:
    driver: bridge


